name: Trigger auto deployment for container-app-wmdg4pmn6agjk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-wmdg4pmn6agjk-AutoDeployTrigger-861743e0-dd43-4011-bd45-1faa38b3f091.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPWMDG4PMN6AGJK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPWMDG4PMN6AGJK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPWMDG4PMN6AGJK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPWMDG4PMN6AGJK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPWMDG4PMN6AGJK_REGISTRY_PASSWORD }}
          containerAppName: container-app-wmdg4pmn6agjk
          resourceGroup: appspacesragapp8b81a43a
          imageToBuild: default/container-app-wmdg4pmn6agjk:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


